### PR TITLE
Change metadata file paths in config to be relative

### LINKED ISSUE #151: Config file paths might be better as relative
Happy to be told otherwise on this, but I think it would be more suitable to save all of the paths that are to files saved alongside the config file (i.e., `pcs_lines`, `dil_lines`, `image_registration`, `default_cam_geom`) as relative paths; other ones, like `img_dir` should stay as absolute paths. This is just because I sometimes move the processing folder, or rename it, to make things clearer for me, but in doing this I break the config file within it. It makes more sense to me to have that whole folder independent of location - you could move it around but it would still work as long as all the files within the folder remain together.

### PR DESCRIPTION
**Pull request by ubdbra001**
This should close #151 

When the config is saved the metadata files saved alongside it are recorded in the file using relative paths (effectively just filenames)

When a config is loaded the list of path parameters are checked and expanded to absolute paths if needed. Not sure if the list of path params are best at the start of `so2_camera_processor.py` or somewhere else. Happy to move them if you think that makes sense. 

I think it captures all the edge cases around loading and saving paths, but if, during testing, you spot any that I haven't caught do let me know.

### CODE REVIEW

**Comment by twVolc** [comment]
This isn't running for me. I'm hitting an error on start-up
```
Traceback (most recent call last):
  File "run_pycam.py", line 1, in <module>
    from pycam.gui.pycam_gui import run_GUI
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\gui\pycam_gui.py", line 14, in <module>
    from pycam.gui.menu import PyMenu
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\gui\menu.py", line 7, in <module>
    from pycam.gui.cfg_menu_frames import geom_settings, process_settings, plume_bg, cell_calib, \
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\gui\cfg_menu_frames.py", line 9, in <module>
    from pycam.gui.figures_analysis import GeomSettings, ProcessSettings, PlumeBackground, DOASFOVSearchFrame, \
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\gui\figures_analysis.py", line 10, in <module>
    from pycam.cfg import pyplis_worker
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\cfg.py", line 16, in <module>
    pyplis_worker = PyplisWorker(config_path=process_settings_path)
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\so2_camera_processor.py", line 321, in __init__
    self.load_config(config_path, "default")
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\so2_camera_processor.py", line 332, in load_config
    self.check_config_paths(file_path)
  File "C:\Users\gg1tcw\Documents\PythonProjects\PyCamTests\PyCamPermanent\pycam\so2_camera_processor.py", line 354, in check_config_paths
    self.check_path(new_value)
AttributeError: 'PyplisWorker' object has no attribute 'check_path'
```

**Comment by twVolc** [comment]
Also just wondering whether this path checker could be made into its own class? That would solve your query about where to the path_params list. I'm just concious that we've already had discussions about `PyplisWorker` being a monster and this is the kind of processing that feels logical to separate out into its own object (could even be saved in `io_py.py` or similar?).

**Comment by ubdbra001** [comment]
> I'm hitting an error on start-up

Looks like part of a future PR snuck into this code. I've removed it and updated the commit history. Give it another go.

> Also just wondering whether this path checker could be made into its own class? That would solve your query about where to the path_params list. I'm just concious that we've already had discussions about `PyplisWorker` being a monster and this is the kind of processing that feels logical to separate out into its own object (could even be saved in `io_py.py` or similar?).

Excellent idea! I'll have a think about how best to do that while you check you're happy that this works how you want it to.

**Comment by ubdbra001** [comment]
> Shall we wait for this to be incorporated into its own object then merge?

I spent a bit more time thinking about this, and it may be worth thinking bigger and creating a class for handling all aspects of the config files (including loading, checking, saving, etc). It'll make `PyplisWorker` a bit more focussed, and may be a way to implement #84. Currently in places `doas`/`ifit` rely on `PyplisWorker` having the config params, it would be good to try and separate that a bit.
But, that is a bigger bit of work, so may be worth incorporating this (so the functionality is there in the next release) and then coming back to it. What do you think?

**Comment by twVolc** [comment]
Yep I agree with you on this. I'll merge this and open a new issue that links to #84 but is dedicated to breaking out config handling to its own class.

**Pull request merged**
