### PR TITLE
Add GUI elements for setting real time processing directories

### LINKED ISSUE #189: Add GUI elements for setting watching_dir and FTP_output_dir config options
as title

### PR DESCRIPTION
**Pull request by ubdbra001**
Adds element for setting:
- FTP output directory
- Watching directory

I copied the layout used for setting post processing directories but if you have other ideas about where these should go I'm happy to change it.

closes #189

### CODE REVIEW

**Comment by twVolc** [comment]
Sorry I've been very slow to this, but this look good to me. One thing it makes me think of is that it might be useful to have a label somewhere in the GUI that displays the current watching directory, just so that you can easily look somwhere in the GUI to understand where it's looking for data. My feeling is that it would go in the analysis window within sequence information, perhaps simply updating the the "Sequence directory" label, I think that would make sense right? We could even add  `(Watched)` to the start of the directory path to indicate that it's not a preloaded sequence but it's a directory that's still currently being watched.

**Comment by tpering** [comment]
This also links to issue #172 I think?

**Comment by ubdbra001** [comment]
No worries, I've been much the same over August.
That's a good idea, I have been wondering where to put that info.
So for post-processing the label would stay the same, and for RTP it would change the label to "Watching directory" and display that directory path. Am I interpreting that correctly?

**Comment by twVolc** [comment]
Yes that' what I'm thinking. It might be easier to not actully change the left-hand label at all, and just append `(Watching)` to the end or start of the file path itself so that only that attribute needs accessing/changing. But if it's just as easy to update the left-hand label too then editing that to "Watching directory" sounds fine too. Either/or.

**Comment by ubdbra001** [comment]
I've added an initial update for this that does as you suggest @twVolc.
It should show this directory with (watching) appended when either: the watching directory is selected or 'start watching' is selected (both through the GUI).
I'm not sure if this is ideal though, as it won't change when a config is loaded.

**Comment by twVolc** [comment]
I guess when a config file is loaded it should show the current sequence that's being shown, but if "Start watching" is clicked it should update to the watch directory. But like you say, this isn't ideal as you could load a config file and want to know what watch directory is currently configured, before telling the program to start watching. So perhaps actually we should have a separate watch directory label within that box so that it's clear what it's set up as, then when it's actually watching we maybe have something displayed to show it's now actually watching that directory (e.g. the (watching)) is added at that point. What do you think?

**Comment by twVolc** [comment]
Also unrelated but I notice this PR is now saying "All checks have failed" following #218. Is this working as anticipated or has that been set up slightly incorrectly? It looks a little less appealing not having the big green button saying it can all merge happily.

**Comment by ubdbra001** [comment]
> Also unrelated but I notice this PR is now saying "All checks have failed" following #218. Is this working as anticipated or has that been set up slightly incorrectly? It looks a little less appealing not having the big green button saying it can all merge happily.

This is because I set it up incorrectly #220 should fix it (though getting Github Actions working correctly is a bit of a pain)

**Comment by twVolc** [comment]
> > Also unrelated but I notice this PR is now saying "All checks have failed" following #218. Is this working as anticipated or has that been set up slightly incorrectly? It looks a little less appealing not having the big green button saying it can all merge happily.
> 
> This is because I set it up incorrectly #220 should fix it (though getting Github Actions working correctly is a bit of a pain)

Not sure if my browser just isn't updating but I'm still seeing this problem on this PR after merging #220. Also it's interesting that it's being implemented having only been pulled to dev at this point, not master? I'm guessing these rules just immediately get applied regardless of the branch?

**Comment by ubdbra001** [comment]
It's not you, they are still failing. I've tested the actions locally and they work, so I'm not sure what's going on.
I don't think it's worth spending more time on it until I've got the rest of the PRs sorted. Unless you find the red cross really annoying?

**Comment by twVolc** [comment]
Yeh like you say, not worth wasting time on it now. It's a little annoying not being able to see the green merge telling me things are fine, but I will get over it!

**Comment by ubdbra001** [comment]
> I guess when a config file is loaded it should show the current sequence that's being shown, but if "Start watching" is clicked it should update to the watch directory. But like you say, this isn't ideal as you could load a config file and want to know what watch directory is currently configured, before telling the program to start watching. So perhaps actually we should have a separate watch directory label within that box so that it's clear what it's set up as, then when it's actually watching we maybe have something displayed to show it's now actually watching that directory (e.g. the (watching)) is added at that point. What do you think?

I think a separate watch label is probably the clearest way of relaying the information at a glance. The other alternative would be to put it in the setup paths menu?

**Comment by twVolc** [comment]
Yes setup paths is probably a sensible place to put this. A dedicated label in the Analysis window might be a useful additional place to hold the info but probably isn't critical. Maybe duplicating things isn't best?

**Comment by ubdbra001** [comment]
Okay, in that case I'll put the button to set the value, and the label displaying the current values for both the `FTP_output_dir` and `watching_dir` settings in the setup paths window.
I think it's better to keep to a single place for setting an option, so I'll remove the buttons I added in the menus.

**Comment by ubdbra001** [comment]
I think I have updated everything as discussed:
- You can see the current settings for the FTP output directory and the Watching directory in the processing settings/setup paths menu
- You can also change these values here from the GUI
- The "Sequence directory" label on the Analysis page will update to show "path (watched)" when RTP is selected

I also did a bit of tidying of the code, have a look and make sure it all looks and works okay for you.

**Comment by ubdbra001** [comment]
> I feel like there was a reason why I made them separate, but I can't recall why off the top of my head.

I had a go with this and there's no technical reason why they can't be set by the same config parameter. I think that my thinking in keeping them separate was to make it clear that `FTP_output_dir` is specifically where the files from the Pi get moved to, and they may or may not be watched/processed. To me the `watching_dir` parameter indicates that they will be processed, and doesn't indicate that this is where the files being transferred via FTP will end up.
We might be able to achieve the same thing by renaming these parameters to something better. I'll be the first to admit that my names are not always the most informative.

**Comment by twVolc** [comment]
Yeh I also have a feeling there's a reason why we separated them, but, like you say, maybe it was mainly just to provide clarity on what each path is setting. Overall though, for simplicity of the GUI - not overwhelming the user with options - now that I think more about it it does make sense to keep them as a single parameter. What's your opinion? 

*I don't think your naming conventions are any worse than mine!!

**Comment by ubdbra001** [comment]
I think having them merged is a good idea as it reduces the complexity of the code (only a little but it helps).
But I am unsure if the name `watching_dir` is informative enough to cover both cases.

The only alternative I can think of is `transfer_dir` and we could update the menu items in the RTP menu to explicitly say they are watching the transfer directory? That feels a bit clearer, not a lot but maybe enough?

**Comment by twVolc** [comment]
Yes `transfer_dir` sounds good to me.

**Comment by ubdbra001** [comment]
Okay, all changed.
Try it out and let me know if you're happy with it.

Once you are I'll probably spend a little time sorting out the merge commits and tidying up the git history before we merge.

**Comment by ubdbra001** [comment]
The FTP output is an artefact that I forgot to remove. I'll do that today.

**Comment by ubdbra001** [comment]
Updated to remove references to `FTP_output_dir`, should all be `transfer_dir` now

**Comment by twVolc** [comment]
This looks good to me. It just ahs some conflicts to resolve before merging. I'm never massively confident I fully understand this bit, so do you think this is something you'd be able to do @ubdbra001 ?

**Comment by ubdbra001** [comment]
Okay, give it one last try before you merge, just to make sure I haven't accidentally lost something when sorting out the history and conflicts.
But if you're happy then we're good to merge.

**Comment by twVolc** [comment]
I'm getting an error when I try to run this:

```
Error: Default value for watching_dir missing.

Reverting to config file supplied with PyCam
Traceback (most recent call last):
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\so2_camera_processor.py", line 329, in __init__
    self.load_config(config_path, "default")
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\so2_camera_processor.py", line 352, in load_config
    checked_config = self.check_config_paths(file_path, raw_config)
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\so2_camera_processor.py", line 381, in check_config_paths
    raise ValueError(f"Default value for {path_param} missing.")
ValueError: Default value for watching_dir missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_pycam.py", line 1, in <module>
    from pycam.gui.pycam_gui import run_GUI
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\gui\pycam_gui.py", line 14, in <module>
    from pycam.gui.menu import PyMenu
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\gui\menu.py", line 7, in <module>
    from pycam.gui.cfg_menu_frames import geom_settings, process_settings, plume_bg, cell_calib, \
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\gui\cfg_menu_frames.py", line 9, in <module>
    from pycam.gui.figures_analysis import (GeomSettings, ProcessSettings, PlumeBackground, DOASFOVSearchFrame,
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\gui\figures_analysis.py", line 10, in <module>
    from pycam.cfg import pyplis_worker
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\cfg.py", line 16, in <module>
    pyplis_worker = PyplisWorker(config_path=process_settings_path)
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\so2_camera_processor.py", line 342, in __init__
    self.load_config(FileLocator.PROCESS_DEFAULTS, "default")
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\so2_camera_processor.py", line 352, in load_config
    checked_config = self.check_config_paths(file_path, raw_config)
  File "C:\Users\thom_\Documents\Work\Python\pycam_dev\PyCamPermanent\pycam\so2_camera_processor.py", line 381, in check_config_paths
    raise ValueError(f"Default value for {path_param} missing.")
ValueError: Default value for watching_dir missing.
```

**Comment by ubdbra001** [comment]
Missed a `watching_dir`, should be okay now.

**Pull request merged**
