### PR TITLE
Fix Doas figure spinboxes

### PR DESCRIPTION
**Pull request by ubdbra001**
Spinboxes now execute a command when a value is entered and then focus is moved away (e.g. by clicking on next box).

Try it out and see if you're happy with the change for the wavlength start/end boxes and if so I can add it to other places too.

### CODE REVIEW

**Comment by twVolc** [comment]
It would be nice if hitting enter also made the change, rather than needing to click on a different box. But this stuff definitely isn't critical so if it's more than a 5 minute job I wouldn't bother!

Just had a quick look at other places this should perhaps be implemented and there aren't necessarily loads where it's critical. The camera window has an update plot button - I guess this could be removed and changes moved to interactions on the spinboxes. But again this isn't that important. A lot of the spinboxes in the analysis window are most likely to be used as a click rather than writing in them.

**Comment by ubdbra001** [comment]
> It would be nice if hitting enter also made the change

Latest commit should add that, try it and let me know if it's okay.

> Just had a quick look at other places this should perhaps be implemented and there aren't necessarily loads where it's critical. The camera window has an update plot button - I guess this could be removed and changes moved to interactions on the spinboxes. But again this isn't that important. A lot of the spinboxes in the analysis window are most likely to be used as a click rather than writing in them.

Would you be able to add a couple of screenshots highlighting which ones I should update?

**Comment by twVolc** [comment]
These are probably the main places. You could remove the update plot button from the camera window, so this would tidy that up a little. There's also the `shift` button in the DOAS window, that might as well be updated to this too.

change_plot1

change_plot

**Comment by ubdbra001** [comment]
Okay, all done.
Random observation: For the 'Figure options' in the 'Analysis window' would it be worth disabling the spin boxes when the 'Auto' checkbox is clicked? I will admit I spent a good minute changing the values in the spin boxes and being perplexed as to why nothing was changing.

**Comment by twVolc** [comment]
> Okay, all done. Random observation: For the 'Figure options' in the 'Analysis window' would it be worth disabling the spin boxes when the 'Auto' checkbox is clicked? I will admit I spent a good minute changing the values in the spin boxes and being perplexed as to why nothing was changing.

Haha yes I think it would!!

**Comment by ubdbra001** [comment]
Done, so I think this is ready to merge. Unless you've spotted something else related that could be fixed here?

**Comment by twVolc** [comment]
This is all excellent! It makes quite a big difference to interactivity

**Pull request merged**
