### PR TITLE
Moved all velocity settings to single frame

### LINKED ISSUE #145: flow_nadeau and cross correlation frames should be moved to tabs in Plume velocity settings
As the title says, this would be a more logical place to display these parts of the GUI

### PR DESCRIPTION
**Pull request by twVolc**
Moved all frames into a single window/option - fixes #145.

TODO add a scrollbar for optical flow window (it goes off the bottom of the screen so can't click Apply)

### CODE REVIEW

**Comment by twVolc** [comment]
@ubdbra001 Sorry for another request. There's no rush on this at all (not a priority as it's just GUI/code tidying) but would you be able to run whatever emission rate tests you have on this branch please? I shouldn't have messed anything up as really it was just moving things around in the GUI, but to tidy things up I did break the Nadeau flow stuff out into its own class `NadeauFlowSettings`, rather than staying in the `CrossCorrelationSettings` class so this involved moving quite a few variables around etc that could affect processing if not correctly implemented. From the tests I've done all functionality seems to be there, working correctly, but it would be good if you could have a go with any proper tests you have (e.g. comparing emission rate outputs, particularly if those tests have a few different configurations of Nadeau flow settings for instance). 

As an aside, having a few emission rate retrieval tests with different settings would probably be a useful thing to have if it isn't there already, as I guess testing just on default settings does indicate whether user interactions with the GUI (or config file loading) make the correct changes to output.

**Comment by ubdbra001** [comment]
I'll have a go at running this later on in the week to see if it has affected any of the results.

**Review by ubdbra001 — APPROVED** [review]
I ran DOAS and Emission processing comparing the current Release (2024.06), Dev (commit: 6f8941), and this branch. They produced identical results.
This was just post-processing so do let me know if you'd like me to try RTP as well.

**Comment by twVolc** [comment]
Excellent, thanks. I'm happy with this then!

**Pull request merged**
